# Smart Air Quality Prediction and Pollution Pattern Analysis Using Data Science with Python

## Major Project
### Course: Data Science with Python

---

### Objectives
- Analyze air quality data
- Perform exploratory data analysis
- Visualize pollution trends
- Apply statistical analysis
- Build machine learning models
- Predict pollution levels

In [1]:
# ==========================================
# Import Required Libraries
# ==========================================

# Data Handling Libraries
import pandas as pd
import numpy as np

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Evaluation Metrics
from sklearn.metrics import mean_squared_error, r2_score

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Display plots properly
%matplotlib inline

In [7]:
# Load Dataset

df = pd.read_csv(r"C:\Users\hp\Downloads\Real Time Air Quality Index.csv")

In [8]:
# Display First 5 Rows

df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Bihar,Begusarai,"Lohiyanagar, Begusarai - BSPCB",27-11-2025 09:00:00,25.427420,86.138861,NH3,4.0,5.0,5.0
1,India,Bihar,Bettiah,"Kamalnath Nagar, Bettiah - BSPCB",27-11-2025 09:00:00,26.803650,84.519540,PM2.5,41.0,223.0,102.0
2,India,Bihar,Bhagalpur,"DM Office_Kachari Chowk, Bhagalpur - BSPCB",27-11-2025 09:00:00,25.251013,86.989001,NO2,6.0,11.0,8.0
3,India,Bihar,Bhagalpur,"Mayaganj, Bhagalpur - BSPCB",27-11-2025 09:00:00,25.265194,87.012947,PM2.5,54.0,113.0,80.0
4,India,Bihar,Bhagalpur,"Mayaganj, Bhagalpur - BSPCB",27-11-2025 09:00:00,25.265194,87.012947,NH3,8.0,15.0,11.0

In [9]:
# Dataset Shape

print("Rows and Columns:", df.shape)

Rows and Columns: (3344, 11)

In [10]:
# Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3344 entries, 0 to 3343
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3344 non-null   object
 1   state          3344 non-null   object
 2   city           3344 non-null   object
 3   station        3344 non-null   object
 4   last_update    3344 non-null   object
 5   latitude       3344 non-null   float64
 6   longitude      3344 non-null   float64
 7   pollutant_id   3344 non-null   object
 8   pollutant_min  3151 non-null   float64
 9   pollutant_max  3151 non-null   float64
 10  pollutant_avg  3151 non-null   float64
dtypes: float64(5), object(6)
memory usage: 287.5+ KB

In [11]:
# Missing Values

df.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    193
pollutant_max    193
pollutant_avg    193
dtype: int64

In [12]:
# Statistical Summary

df.describe()

          latitude    longitude  pollutant_min  pollutant_max  pollutant_avg
count  3344.000000  3344.000000    3151.000000    3151.000000    3151.000000
mean     22.783891    78.671825      36.297049     102.244367      62.671533
std       5.474393     4.852910      46.269157     114.243730      77.706066
min       8.514909    70.909168       1.000000       1.000000       1.000000
25%      19.089328    75.642737       6.000000      18.000000      11.000000
50%      23.549395    77.321700      18.000000      62.000000      31.000000
75%      27.213494    80.649110      48.000000     144.000000      88.000000
max      34.066206    94.636574     334.000000     500.000000     434.000000

In [13]:
# Duplicate Rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [14]:
# Unique Pollutants

df['pollutant_id'].unique()

array(['NH3', 'PM2.5', 'NO2', 'SO2', 'CO', 'PM10', 'OZONE'], dtype=object)